import fs from "node:fs";

function invariant(condition, message) {
  if (!condition) throw new Error(message);
}

function integer(value, name, minimum, maximum) {
  invariant(Number.isInteger(value) && value >= minimum && value <= maximum,
    `${name} must be an integer from ${minimum} through ${maximum}`);
  return value;
}

function byte(value) {
  return `$${(value & 0xff).toString(16).padStart(2, "0").toUpperCase()}`;
}

export function loadEntityEffectsDefinition(sourcePath) {
  const definition = JSON.parse(fs.readFileSync(sourcePath, "utf8"));
  invariant(definition.formatVersion === 1, "Unsupported entity-effects formatVersion");
  const coordinates = definition.coordinateSystem;
  integer(coordinates?.gameplayTopScanline, "coordinateSystem.gameplayTopScanline", 0, 255);
  integer(coordinates?.gameplayBottomExclusive,
    "coordinateSystem.gameplayBottomExclusive", 1, 256);
  integer(coordinates?.logicalRows, "coordinateSystem.logicalRows", 1, 32);
  invariant(coordinates.gameplayTopScanline === 24,
    "Entity gameplay must begin below the divider at scanline 24");
  invariant(coordinates.gameplayBottomExclusive === 200,
    "Entity gameplay must end after scanline 199");
  invariant(coordinates.logicalRows === 22 &&
    coordinates.gameplayBottomExclusive - coordinates.gameplayTopScanline ===
      coordinates.logicalRows * 8,
  "Entity coordinates must describe exactly 22 eight-scanline ring rows");

  const pools = definition.pools;
  invariant(pools?.interactiveSlots === 4, "Interactive pool must contain four slots");
  invariant(pools.interactiveActiveLimit === 1,
    "First debris slice must enable exactly one interactive entity");
  invariant(pools.effectSlots === 6 && pools.effectActiveLimit === 0,
    "Transient effects must remain disabled in the first slice");
  invariant(pools.stateAddress === 0x8000 && pools.stateBytes === 0x100,
    "Entity/effects state must occupy only $8000-$80FF");
  invariant(pools.codeAddress === 0x9100 && pools.codeReservedBytes === 0x0f00,
    "ENTITY_CODE must occupy only $9100-$9FFF");

  const spawn = definition.spawn;
  integer(spawn?.initialDelayFrames, "spawn.initialDelayFrames", 1, 255);
  integer(spawn?.repeatDelayFrames, "spawn.repeatDelayFrames", 1, 255);
  integer(spawn?.rngSeed, "spawn.rngSeed", 1, 255);

  invariant(Array.isArray(definition.archetypes) && definition.archetypes.length === 1,
    "First slice must contain exactly one archetype");
  const archetype = definition.archetypes[0];
  invariant(archetype.id === "neutral-debris" && archetype.type === 1,
    "First archetype must be neutral-debris type 1");
  for (const name of [
    "initialState", "flags", "updateProfile", "renderProfile", "collisionCategory",
    "widthHpos", "heightScanlines", "contactDamageUnits", "movementNumerator",
    "movementDenominator", "lifetime", "hitPoints", "spawnPolicy", "sfxEventId",
  ]) integer(archetype[name], `archetypes[0].${name}`, 0, 255);
  integer(archetype.initialVx, "archetypes[0].initialVx", -128, 127);
  integer(archetype.initialVy, "archetypes[0].initialVy", -128, 127);
  invariant(archetype.widthHpos === 4 && archetype.heightScanlines === 8,
    "First debris must occupy exactly one ANTIC 4 cell");
  invariant(archetype.contactDamageUnits === 1,
    "First debris contact must cause one HULL unit of damage");
  invariant(archetype.initialVx === 0 && archetype.initialVy === 8,
    "First debris must move one row vertically and never laterally");
  invariant(Array.isArray(archetype.glyphRows) && archetype.glyphRows.length === 8,
    "neutral-debris glyph must contain eight rows");
  archetype.glyphRows.forEach((row, index) =>
    integer(row, `archetypes[0].glyphRows[${index}]`, 0, 255));
  return definition;
}

export function compileEntityEffects(definition) {
  const archetype = definition.archetypes[0];
  const descriptor = Uint8Array.from([
    archetype.initialState,
    archetype.flags,
    archetype.updateProfile,
    archetype.renderProfile,
    archetype.collisionCategory,
    archetype.widthHpos,
    archetype.heightScanlines,
    archetype.contactDamageUnits,
    archetype.initialVx,
    archetype.initialVy,
    archetype.movementNumerator,
    archetype.movementDenominator,
    archetype.lifetime,
    archetype.hitPoints,
    archetype.spawnPolicy,
    archetype.sfxEventId,
  ]);
  invariant(descriptor.length === 16, "Entity archetype descriptor must remain 16 bytes");
  return Object.freeze({
    ...definition,
    descriptor,
    glyph: Uint8Array.from(archetype.glyphRows),
  });
}

export function renderEntityEffectsCa65Include(asset) {
  const { coordinateSystem: coordinates, pools, spawn } = asset;
  return [
    "; Generated from assets/graphics/entity-effects.json by scripts/entity-effects.mjs.",
    "; Do not edit this file by hand.",
    `ENTITY_GAMEPLAY_TOP = ${coordinates.gameplayTopScanline}`,
    `ENTITY_GAMEPLAY_BOTTOM = ${coordinates.gameplayBottomExclusive}`,
    `ENTITY_LOGICAL_ROWS = ${coordinates.logicalRows}`,
    `ENTITY_SLOT_COUNT = ${pools.interactiveSlots}`,
    `ENTITY_ACTIVE_LIMIT = ${pools.interactiveActiveLimit}`,
    `EFFECT_SLOT_COUNT = ${pools.effectSlots}`,
    `EFFECT_ACTIVE_LIMIT = ${pools.effectActiveLimit}`,
    `ENTITY_STATE_ADDRESS = $${pools.stateAddress.toString(16).toUpperCase()}`,
    `ENTITY_STATE_BYTES = $${pools.stateBytes.toString(16).toUpperCase()}`,
    `ENTITY_CODE_ADDRESS = $${pools.codeAddress.toString(16).toUpperCase()}`,
    `ENTITY_CODE_RESERVED_BYTES = $${pools.codeReservedBytes.toString(16).toUpperCase()}`,
    `ENTITY_INITIAL_SPAWN_DELAY = ${spawn.initialDelayFrames}`,
    `ENTITY_REPEAT_SPAWN_DELAY = ${spawn.repeatDelayFrames}`,
    `ENTITY_RNG_SEED = $${spawn.rngSeed.toString(16).padStart(2, "0").toUpperCase()}`,
    "ENTITY_ARCHETYPE_DESCRIPTOR_BYTES = 16",
    "ENTITY_DESC_INITIAL_STATE = 0",
    "ENTITY_DESC_FLAGS = 1",
    "ENTITY_DESC_UPDATE_PROFILE = 2",
    "ENTITY_DESC_RENDER_PROFILE = 3",
    "ENTITY_DESC_COLLISION_CATEGORY = 4",
    "ENTITY_DESC_WIDTH_HPOS = 5",
    "ENTITY_DESC_HEIGHT_SCANLINES = 6",
    "ENTITY_DESC_CONTACT_DAMAGE = 7",
    "ENTITY_DESC_INITIAL_VX = 8",
    "ENTITY_DESC_INITIAL_VY = 9",
    "ENTITY_DESC_MOVEMENT_NUMERATOR = 10",
    "ENTITY_DESC_MOVEMENT_DENOMINATOR = 11",
    "ENTITY_DESC_LIFETIME = 12",
    "ENTITY_DESC_HIT_POINTS = 13",
    "ENTITY_DESC_SPAWN_POLICY = 14",
    "ENTITY_DESC_SFX_EVENT = 15",
    "ENTITY_TYPE_DEBRIS = 1",
    "ENTITY_STATE_ACTIVE = 1",
    "ENTITY_FLAG_WORLD_ATTACHED = $01",
    "ENTITY_FLAG_COLLIDE_PLAYER = $04",
    "ENTITY_FLAG_PERSIST_LIFE = $10",
    "ENTITY_FLAG_CLEAR_ON_SECTOR = $20",
    "ENTITY_COLLISION_PLAYER_DAMAGE = 1",
    "ENTITY_EVENT_WORLD_ROW_ADVANCED = $01",
    ".macro EMIT_ENTITY_ARCHETYPE_DESCRIPTORS",
    `    .byte ${[...asset.descriptor].map(byte).join(",")}`,
    ".endmacro",
    ".macro EMIT_ENTITY_DEBRIS_GLYPH",
    `    .byte ${[...asset.glyph].map(byte).join(",")}`,
    ".endmacro",
    "",
  ].join("\n");
}
